Repository GraphQL-Portal/graphql-portal-dashboard, pull requests merged in 2021-02, with the labels that each got.

#189 (enhancement) Some minor enhancements for My Data sources page.
  packages/backend/src/common/middlewares/auth.middleware.ts
  packages/backend/src/modules/source/source.schema.gql
  packages/frontend/src/model/DataSources/queries/useSources.ts
  packages/frontend/src/presenter/DataSources/helpers/general.ts
  packages/frontend/src/view/DataSources/DataSources/AvailableList.tsx
  packages/frontend/src/view/DataSources/DataSources/ConnectedList.tsx
  packages/frontend/src/view/DataSources/DataSources/types.ts
  packages/frontend/src/view/DataSources/constants.ts
  packages/frontend/src/view/DataSources/helpers.ts
Labels: enhancement

#190 (enhancement) Minor stylistic enhancements of Data Sources & Tranforms
  packages/frontend/src/model/DataSources/queries/useSources.ts
  packages/frontend/src/model/GatewayNodes/queries/useGateways.ts
  packages/frontend/src/presenter/DataSources/constants.ts
  packages/frontend/src/presenter/DataSources/helpers/formatTransformLabel.ts
  packages/frontend/src/presenter/DataSources/helpers/transformHandler.ts
  packages/frontend/src/presenter/DataSources/useTransforms.ts
  packages/frontend/src/types/DataSource.ts
  packages/frontend/src/types/Gateway.ts
  packages/frontend/src/types/index.ts
  packages/frontend/src/view/DataSources/AddDataSource/AddDataSource.tsx
  packages/frontend/src/view/DataSources/ContentfulHandler/ContentfulHandler.tsx
  packages/frontend/src/view/DataSources/DataSources/AvailableList.tsx
  packages/frontend/src/view/DataSources/FhirHandler/FhirHandler.tsx
  packages/frontend/src/view/DataSources/GRPCHandler/GRPCHandler.tsx
  packages/frontend/src/view/DataSources/MySQLHandler/MySQLHandler.tsx
  packages/frontend/src/view/DataSources/Neo4jHandler/Neo4jHandler.tsx
  packages/frontend/src/view/DataSources/OdataHandler/OdataHandler.tsx
  packages/frontend/src/view/DataSources/PostGraphileHandler/PostGraphileHandler.tsx
  packages/frontend/src/view/DataSources/SlackHandler/SlackHandler.tsx
  packages/frontend/src/view/DataSources/SoapHandler/SoapHandler.tsx
  packages/frontend/src/view/DataSources/SourceTransforms/List.tsx
  packages/frontend/src/view/DataSources/SourceTransforms/SourceTransforms.tsx
  packages/frontend/src/view/DataSources/ThriftHandler/ThriftHandler.tsx
  packages/frontend/src/view/DataSources/constants.ts
  packages/frontend/src/view/DataSources/helpers.ts
  packages/frontend/src/view/GatewayNodes/List.tsx
  packages/frontend/src/view/GatewayNodes/types.ts
  packages/frontend/src/view/Navigation/Main/constants.ts
  packages/frontend/src/view/Sidebar/Sidebar.tsx
  packages/frontend/src/view/Users/CreateUser/CreateUser.tsx
Labels: enhancement

#225 [F] types for useQuery and useMutation
  package.json
  packages/frontend/src/model/ApiDefs/commands/useCreateApiDef.ts
  packages/frontend/src/model/ApiDefs/commands/useDeleteApiDef.ts
  packages/frontend/src/model/DataSources/commands/useCreateSource.ts
  packages/frontend/src/model/DataSources/commands/useDeleteSource.ts
  packages/frontend/src/model/DataSources/commands/useUpdateSource.ts
  packages/frontend/src/model/DataSources/queries/useSources.ts
  packages/frontend/src/model/GatewayNodes/queries/useGateways.ts
  packages/frontend/src/model/Login/commands/useLogin.ts
  packages/frontend/src/model/ResetPassword/commands/useResetPassword.ts
  packages/frontend/src/model/ResetPasswordRequest/commands/useResetPasswordRequest.ts
  packages/frontend/src/model/SignUp/commands/useSignUp.ts
  packages/frontend/src/model/Users/commands/useBlockUser.ts
  packages/frontend/src/model/Users/commands/useCreateUser.ts
  packages/frontend/src/model/Users/commands/useDeleteUser.ts
  packages/frontend/src/model/Users/commands/useUnblockUser.ts
  packages/frontend/src/model/Users/commands/useUpdateUser.ts
  packages/frontend/src/model/Users/queries/useUsers.ts
  packages/frontend/src/presenter/DataSources/helpers/index.ts
  packages/frontend/src/presenter/DataSources/helpers/sortSourcesByName.ts
  packages/frontend/src/presenter/DataSources/useDataSources.ts
  packages/frontend/src/types/Apollo.ts
  packages/frontend/src/types/index.ts
Labels: enhancement

#226 [F] abstract over @material-ui/icons
  packages/frontend/src/icons/index.ts
  packages/frontend/src/ui/Empty/Icon.tsx
  packages/frontend/src/ui/Header/HeaderBackButton.tsx
  packages/frontend/src/ui/Widgets/WidgetHeader/WidgetHeader.tsx
  packages/frontend/src/view/DataSources/DataSources/AvailableList.tsx
  packages/frontend/src/view/DataSources/DataSources/ConnectedList.tsx
  packages/frontend/src/view/DataSources/SourceTransforms/List.tsx
  packages/frontend/src/view/Form/ObjectArray/ObjectArray.tsx
  packages/frontend/src/view/Form/StringArray/StringArray.tsx
  packages/frontend/src/view/MyAPI/List/List.tsx
  packages/frontend/src/view/Navigation/Main/constants.ts
  packages/frontend/src/view/Users/List.tsx
Labels: enhancement

#227 [F] refactor MyApi list
  packages/frontend/src/presenter/ApiDefs/helpers.ts
  packages/frontend/src/types/Api.ts
  packages/frontend/src/view/MyAPI/List/List.tsx
  packages/frontend/src/view/MyAPI/List/types.ts
  packages/frontend/src/view/MyAPI/MyApi/Empty.tsx
  packages/frontend/src/view/MyAPI/MyApi/List.tsx
  packages/frontend/src/view/MyAPI/MyApi/MyAPI.tsx
  packages/frontend/src/view/MyAPI/MyApi/constants.ts
  packages/frontend/src/view/MyAPI/MyApi/index.ts
  packages/frontend/src/view/MyAPI/Routes.tsx
Labels: enhancement

#232 [F] show delete api Dialog after click on Button
  packages/frontend/src/presenter/ApiDefs/index.ts
  packages/frontend/src/presenter/ApiDefs/useDeleteAPI.ts
  packages/frontend/src/presenter/ApiDefs/useMyApi.ts
  packages/frontend/src/types/Api.ts
  packages/frontend/src/view/Dialogs/constants.ts
  packages/frontend/src/view/MyAPI/DeleteAPI/DeleteAPI.tsx
  packages/frontend/src/view/MyAPI/DeleteAPI/index.ts
  packages/frontend/src/view/MyAPI/DeleteAPI/useStyles.ts
  packages/frontend/src/view/MyAPI/MyApi/List.tsx
  packages/frontend/src/view/MyAPI/MyApi/MyAPI.tsx
Labels: feature

#236 (enhancement) Enhancement/minor modifications
  .gitignore
  packages/backend/src/common/interface/gateway.interface.ts
  packages/backend/src/common/middlewares/auth.middleware.ts
  packages/backend/src/modules/gateway/gateway.schema.gql
  packages/backend/src/modules/gateway/gateway.service.ts
  packages/backend/src/modules/user/token.service.ts
  packages/backend/src/test/integration/gateway.integration-spec.ts
  packages/frontend/src/view/ApiActivity/Empty.tsx
  packages/frontend/src/view/ApiMetrics/ApiMetrics.tsx
  packages/frontend/src/view/Dashboard/Dashboard.tsx
Labels: enhancement

#238 [F] add beta badge to logo
  packages/frontend/src/view/MyAPI/Edit/Edit.tsx
  packages/frontend/src/view/MyAPI/constants.ts
  packages/frontend/src/view/Sidebar/Sidebar.tsx
  packages/frontend/src/view/Sidebar/useStyles.ts
Labels: feature

#239 (feat) Up2date ApiDef fields to Backend
  packages/backend/src/modules/api-def/api-def.schema.gql
  packages/backend/src/modules/app.module.ts
Labels: feature

#253 [F] filter handlers and transforms
  packages/frontend/src/presenter/DataSources/constants.ts
  packages/frontend/src/presenter/DataSources/helpers/filterObjectByList.ts
  packages/frontend/src/presenter/DataSources/helpers/index.ts
  packages/frontend/src/presenter/DataSources/useAvailableSources.ts
  packages/frontend/src/presenter/DataSources/useDataSources.ts
  packages/frontend/src/view/DataSources/helpers.ts
Labels: enhancement

#263 (fix) Hide Country metrics when empty
  packages/frontend/src/view/Dashboard/Dashboard.tsx
Labels: bug

#262 (fix) Update createApiDef input type
  packages/backend/src/modules/api-def/api-def.schema.gql
Labels: bug

#266 [F] add keys to buttons in ButtonGroup
  packages/frontend/src/ui/ButtonGroup/ButtonGroup.tsx
  packages/frontend/src/utils/getKeyFromText.ts
Labels: enhancement

#274 (enhancement) OpenAPI form handler minor enhancements
  packages/frontend/src/presenter/DataSources/constants.ts
  packages/frontend/src/view/DataSources/DataSources/constants.ts
  packages/frontend/src/view/DataSources/OpenapiHandler/OpenapiHandler.tsx
  packages/frontend/src/view/DataSources/helpers.ts
Labels: enhancement
