Repository GraphQL-Portal/graphql-portal-dashboard, pull requests merged in 2021-04, with the labels that each got.

#532 (feat) New Dashboard Charts
  .changeset/thick-boats-collect.md
  packages/backend/src/modules/metric/interfaces/api-metric.interface.ts
  packages/backend/src/modules/metric/interfaces/country-metric.interface.ts
  packages/backend/src/modules/metric/interfaces/index.ts
  packages/backend/src/modules/metric/interfaces/metric-filter.interface.ts
  packages/backend/src/modules/metric/interfaces/metric.interface.ts
  packages/backend/src/modules/metric/metric.resolver.ts
  packages/backend/src/modules/metric/metric.schema.gql
  packages/backend/src/modules/metric/metric.service.ts
  packages/backend/src/test/integration/metric.integration-spec.ts
  packages/backend/src/test/unit/metric.service.spec.ts
  packages/frontend/package.json
  packages/frontend/src/App.tsx
  packages/frontend/src/model/Metrics/queries/index.ts
  packages/frontend/src/model/Metrics/queries/useApiActivity.ts
  packages/frontend/src/model/Metrics/queries/useApiMetrics.ts
  packages/frontend/src/model/Metrics/queries/useMetrics.ts
  packages/frontend/src/presenter/ApiDefs/helpers/getUrlFromGatewayNodes.ts
  packages/frontend/src/presenter/Metrics/index.ts
  packages/frontend/src/presenter/Metrics/useApiActivityMetrics.ts
  packages/frontend/src/presenter/Metrics/useApiMetrics.ts
  packages/frontend/src/presenter/Metrics/useDashboardMetrics.ts
  packages/frontend/src/presenter/Metrics/useMetrics.ts
  packages/frontend/src/types/ButtonGroup.ts
  packages/frontend/src/types/Forms/components.ts
  packages/frontend/src/types/Metrics.ts
  packages/frontend/src/ui/ButtonGroup/ButtonGroup.tsx
  packages/frontend/src/ui/DatePicker/DatePicker.tsx
  packages/frontend/src/ui/DatePicker/index.ts
  packages/frontend/src/ui/Select/Select.tsx
  packages/frontend/src/ui/index.ts
  packages/frontend/src/utils/checkHandler.ts
  packages/frontend/src/utils/formatArgumentLabel.ts
  packages/frontend/src/utils/formatValueLabel.ts
  packages/frontend/src/utils/getDateChunks.ts
  packages/frontend/src/utils/index.ts
  packages/frontend/src/view/ApiMetrics/ApiMetrics.tsx
  packages/frontend/src/view/ApiMetrics/useStyles.ts
  packages/frontend/src/view/Content/useStyles.ts
  packages/frontend/src/view/Dashboard/Dashboard.tsx
  packages/frontend/src/view/Dashboard/useStyles.ts
  packages/frontend/src/view/MetricChart/CountryChart.tsx
  packages/frontend/src/view/MetricChart/FailureRequestRateChart.tsx
  packages/frontend/src/view/MetricChart/LatencyRequestChart.tsx
  packages/frontend/src/view/MetricChart/RequestChart.tsx
  packages/frontend/src/view/MetricChart/SuccessFailureChart.tsx
  packages/frontend/src/view/MetricChart/constants.ts
  packages/frontend/src/view/MetricChart/helpers.ts
  packages/frontend/src/view/MetricChart/index.ts
  yarn.lock
Labels: feature

#533 (feat) Update titles & descriptions of connectors
  .changeset/gold-pianos-attack.md
  packages/frontend/src/presenter/DataSources/constants.ts
  packages/frontend/src/presenter/DataSources/helpers/createTransformList.ts
  packages/frontend/src/presenter/DataSources/helpers/formatTransformLabel.ts
  packages/frontend/src/presenter/DataSources/helpers/formatTransformStrings.ts
  packages/frontend/src/view/DataSources/DataSources/AvailableList.tsx
  packages/frontend/src/view/DataSources/DataSources/ConnectedList.tsx
  packages/frontend/src/view/DataSources/DataSources/constants.ts
  packages/frontend/src/view/DataSources/SourceTransforms/Available.tsx
  packages/frontend/src/view/DataSources/SourceTransforms/List.tsx
  packages/frontend/src/view/DataSources/constants.ts
  packages/frontend/src/view/DataSources/helpers.ts
Labels: enhancement

#611 [F] abstract over FormLabel
  .changeset/sour-cougars-cover.md
  packages/frontend/src/types/Forms/components.ts
  packages/frontend/src/ui/Form/FormLabel.tsx
  packages/frontend/src/ui/Form/FormLabelStart.tsx
  packages/frontend/src/ui/Form/index.ts
  packages/frontend/src/ui/Form/useStyles.ts
  packages/frontend/src/view/ApiDefs/Edit/EditHeader.tsx
  packages/frontend/src/view/ApiDefs/Form/CacheTransforms.tsx
  packages/frontend/src/view/ApiDefs/Form/General.tsx
  packages/frontend/src/view/ApiDefs/Form/IP.tsx
  packages/frontend/src/view/ApiDefs/Form/Schema.tsx
  packages/frontend/src/view/ApiDefs/Form/useStyles.ts
  packages/frontend/src/view/DataSources/GRPCHandler/GRPCHandler.tsx
  packages/frontend/src/view/DataSources/GraphQLHandler/GraphQLHandler.tsx
  packages/frontend/src/view/DataSources/Neo4jHandler/Neo4jHandler.tsx
  packages/frontend/src/view/DataSources/OdataHandler/OdataHandler.tsx
  packages/frontend/src/view/DataSources/OpenapiHandler/OpenapiHandler.tsx
  packages/frontend/src/view/DataSources/PostGraphileHandler/PostGraphileHandler.tsx
  packages/frontend/src/view/DataSources/PrefixTransform/PrefixTransform.tsx
  packages/frontend/src/view/DataSources/RenameTransform/RenameTransform.tsx
  packages/frontend/src/view/DataSources/ThriftHandler/ThriftHandler.tsx
Labels: enhancement

#612 [F] fix openapi handler layout
  .changeset/red-apes-jam.md
  packages/frontend/src/view/DataSources/OpenapiHandler/SelectQueryOrMutationFieldConfig.tsx
  packages/frontend/src/view/DataSources/OpenapiHandler/useStyles.ts
Labels: bug, enhancement

#613 [F] fix json schema validation
  packages/frontend/src/presenter/DataSources/useJsonSchemaHandler.ts
  packages/frontend/src/view/DataSources/JsonSchemaHandler/Operations.tsx
Labels: bug
